vich_uploader:
    db_driver: orm

    mappings:
        ouvrages_image:
            uri_prefix: /uploads/ouvrages
            upload_destination: '%kernel.project_dir%/public/uploads/ouvrages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
